### ISSUE TITLE
interactive slider pendulum/torque_slider_demo.py 

### ISSUE THREAD

**Issue by CatchMeFastFat** [RussTedrake/underactuated#109]
It works for me by adding this at the top:
`from pylab import *`

and replacing `simulator.StepTo(args.duration)` with 

```
plt.pause(0.1)
for i in range(1000000):
	plt.pause(0.000000001)
	simulator.StepTo(i)
```

It's not a good solution, but from my understanding is that simulator is a C++ code and I don't understand how it would interactively updated from mathplotlib?

**Comment by RussTedrake** [comment]
what platform are you on?  (still on docker running ubuntu?)

**Comment by RussTedrake** [comment]
and are you sure you are up to date, because we do exactly this already:
https://github.com/RussTedrake/underactuated/blob/master/src/underactuated/pyplot_visualizer.py#L45

**Comment by peteflorence** [comment]
Yes the effects of plt.pause we’ve found to be very platform specific.
Would be helpful if you can note all platform details

**Comment by CatchMeFastFat** [comment]
docker running ubuntu16.04. My host is archlinux .(uname -a inside docker gives arch aswell!)

So why checking for MacOSX only? Does it work normally on ubunto?

**Comment by RussTedrake** [comment]
at some point we dropped the macosx check and pause on all platforms.
