### ISSUE TITLE
planar rigid body visualization minor requests

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/underactuated#112]
the rimless wheel sim in #111 reveals two small quirks.

- cylinders viewed along their long axis are viewed by their bounding box instead of as a circle. 
- xlim and ylim don't actual change the shape of the figure, so I get a LOT of ground.

**Comment by gizatt** [comment]
I can patch (1), but that seems like something that ought to be fixed upstream:

```Warning: DrakeShapes::Cylinder::getPoints(): This method returns the vertices of the cylinder''s bounding-box```

(2) could be addressed in two ways:
- Set the figure's size directly (which is how I do it in the problem sets right now):
```
visualizer = builder.AddSystem(PlanarRigidBodyVisualizer(tree,
                                                         xlim=[-8., 8.],
                                                         ylim=[-4., 4.]))
builder.Connect(rimless_wheel.get_output_port(1), visualizer.get_input_port(0))
visualizer.fig.set_size_inches(8, 4)
```
- Try to do this automatically, inferred from the relative sizes of xlim and ylim. PR I just opened makes a stab at that -- seems to work OK.
