### ISSUE TITLE
controllability vs fully-actuated

### ISSUE THREAD

**Issue by CatchMeFastFat** [RussTedrake/underactuated#133]
As I can understand, the rank condition is almost the same and they seem to be the same concept.

Could you please correct or approve this?

**Comment by RussTedrake** [comment]
Please read the "controllability vs underactuated" section in http://underactuated.csail.mit.edu/underactuated.html?chapter=acrobot

**Comment by CatchMeFastFat** [comment]
Thanks. I was reading chapter 1.
