### ISSUE TITLE
Cable-driven robots can be partially underactuated

### ISSUE THREAD

**Issue by aarchiba** [RussTedrake/underactuated#158]
The simplest example is a one-dimensional cable-driven robot actuated by a single motor that winds a cable the robot hangs from. If the actuator is falling at 1g the motor has at best unidirectional control over the motion. Of course this robot is fairly trivial, but people are building two-dimensional graffiti bots that hang from two cables and can move over a building wall; they suffer the same sort of constraint, and motion planning is nontrivial. More common is to overconstrain such robots; for example to use eight cables for a six-axis robot. I believe this is what is used for coarse positioning of the receiver room of the Chinese radio telescope FAST. These overconstrained systems always operate near but not in the going-slack region (which has a complicated shape), and many of them (okay not FAST) are interesting for rapid motion, since no motors need be moved.

**Comment by peteflorence** [comment]
Is there somewhere in Russ’s text that says cable-driven robots can never be underactuated?

**Comment by aarchiba** [comment]
No, this was in response to: "Admittedly, this permits the existence of a gray area, where we would prefer to avoid describing the system as either fully- or underactuated (we should instead only describe its states); but if you find a physical system that is sort of "half and half", then do let me know!"

**Comment by peteflorence** [comment]
:) 👍
