### ISSUE TITLE
Double Integrator Visualization

### ISSUE THREAD

**Issue by znewman01** [RussTedrake/underactuated#209]
There's a [double integrator TODO](https://github.com/RussTedrake/underactuated/blob/master/src/double_integrator/value_iteration.py#L114) about animation. In the course of my final project I wrote a simple PyPlotVisualizer for the double integrator:

![double_integrator](https://user-images.githubusercontent.com/873857/57095060-f4ad0f80-6cdf-11e9-8e99-7f73899fcc9c.gif)

If you'd like, I can tweak it/clean it up and send a PR, but if you were envisioning something different, no worries. Just say the word either way.

P.S. there's a minor mismatch in the system implementation: [`__init__`](https://github.com/RussTedrake/underactuated/blob/master/src/double_integrator/value_iteration.py#L18-L19) declares a 1-output system with 2 state variables but [`DoCalcVectorOutput`](https://github.com/RussTedrake/underactuated/blob/master/src/double_integrator/value_iteration.py#L26-L28) tries to copy the 2 state variables into the output 1-vector. Two obvious fixes:

- [only output the position](https://github.com/znewman01/underactuated/commit/aaec62c89d905fe34c683fb5d7748b5551a65bf4)
- [declare two outputs](https://github.com/znewman01/underactuated/commit/c76db730e4d6d960ded8e09a4728e642b091af93)

Let me know which you'd prefer.

**Comment by RussTedrake** [comment]
That would be fantastic.  Thanks Zack!

For the dimension mismatch, we've often had visualizers which take the full state as input (e.g. the Quadrotor2dVisualizer) even though they effectively discard the velocity variables.  I slightly prefer that to adding additional ports.
