### ISSUE TITLE
promlem on double_pendulum/simulate.py

### ISSUE THREAD

**Issue by RamiSketcher** [RussTedrake/underactuated#228]
Hello there!
hope you are doing good,

Isn't the pendulum has a sphere at the end instead of a box?!

![Screenshot from 2019-09-02 20-53-57](https://user-images.githubusercontent.com/45199723/64133445-67391380-cdd6-11e9-9e22-bc441eb5e08d.png)

I'm using virtualbox of Ubuntu 18.04 LTS and I ran this installation [Drake](http://underactuated.csail.mit.edu/underactuated.html?chapter=drake).

-----------------------------
Best regards.

**Comment by RussTedrake** [comment]
Indeed.  Thanks for reporting it.  I've just PR'd the fix.
