### ISSUE TITLE
Is algorithm accelerating also part of the problem set?

### ISSUE THREAD

**Issue by vinbo** [RussTedrake/underactuated#232]
When I was working on the pset 3.8, the swing up and lqr combined control, there were 8 intial conditions in the test_set_3.py:
conditions_that_should_converge = [
            np.array([0., 0., 0., 0.]) ,
            np.array([math.pi, 0., 0., 0.]),
            np.array([3*math.pi, 0., 0., 0.]),
            np.array([0., -100., 0., 0.]),
            np.array([0., 0., 0., 20.]),
            np.random.random(4), # Three random initial conditions for fun
            np.random.random(4),
            np.random.random(4)
]
I found I always failed at the 6th or 7th data, for the error info "Test Failed: u'Timed Out' ", and i swapped the  last 3 condition to the front, and all the three passed, and failed at the last initial contidion. Not until then did I realize that my algorithm did not make mistake.
So,  my question is, are the last 3 random conditons really part of problem set of the course in the first place and I still need to accelerate my algorithm, or the last 3 random guys are just added after "just for fun" and I need to delete them for the rational score ?

**Comment by weigao95** [comment]
Yes, I think random initial condition is part of problem set and you might need to make your controller converge faster. You may add print command in the test script to see whether it converges.
