### ISSUE TITLE
The way fuel cost is calculated in test_set_4

### ISSUE THREAD

**Issue by vinbo** [RussTedrake/underactuated#239]
in line 139
fuel_consumption = (u_traj**2).sum()

the calculation does not take the integration step into account. But the result should not be affected by number of time steps or refinement, right?

**Comment by TobiaMarcucci** [comment]
That was a correct point. I saw it too last year.

Closing this since the check is not there anymore in the new version http://underactuated.mit.edu/trajopt.html#section8.
