### ISSUE TITLE
Two typos in problem set 5

### ISSUE THREAD

**Issue by vinbo** [RussTedrake/underactuated#243]
set_5_grasp_analysis.ipynb  :
6th code cell, line 9: 
"Initial volume", volume
-->　print "Initial volume", volume

planar_hand.py:
introdution of def ComputeControlInput()
 Outputs:
        A 1-d numpy array of length self.nq joint torques
--> self.nu

**Comment by TobiaMarcucci** [comment]
Closing since these psets will be rewritten completely and these are minor typos (the first, for example, is a python 2 issue: now only python 3 is supported).
