### ISSUE TITLE
Visibility of the underactuated folder in Bazel

### ISSUE THREAD

**Issue by TobiaMarcucci** [RussTedrake/underactuated#268]
At the moment it is not possible to test python code outside `underactuated/underactuated` which requires to import underactuated files (e.g. `ManipulatorDynamics`). This because the visibility in the`underactuated/underactuated` [BUILD.bazel file](https://github.com/RussTedrake/underactuated/blob/master/underactuated/BUILD.bazel) is set to `visibility = [":__subpackages__"]`. Making this public (`visibility = ["//visibility:public"]`) solves the problem, but I'm not sure it's the right solution.

**Comment by RussTedrake** [comment]
I think it is the right solution.  Please do update it.  Thanks!
