### ISSUE TITLE
urdf reference in dynamics.ipynb

### ISSUE THREAD

**Issue by femust** [RussTedrake/underactuated#294]
In _dynamics.ipynb_, there is a reference to urdf file double_pendulum.urdf, but it seems that the url is incorrect. So despite, `https://github.com/RussTedrake/underactuated/blob/master/underactuated/double_pendulum/double_pendulum.urdf`
should be probably
`https://github.com/RussTedrake/underactuated/blob/master/underactuated/models/double_pendulum.urdf`

**Comment by RussTedrake** [comment]
great catch.  thanks!
