### ISSUE TITLE
MathJax doesn't render on underactuated.html

### ISSUE THREAD

**Issue by Joaoloula** [RussTedrake/underactuated#303]
Shows up on the chapter 7 sub-header "Numerical solutions for $J^*$". Reproducible on firefox and chrome. I don't know enough html to know what the problem is, since 1) the header is the same as on other pages, where MathJax works 2) it's not an equation typo/a function of the placement on text as I tested adding other MathJax commands and that won't render either.

**Comment by RussTedrake** [comment]
Good catch.   Thanks!   (I deferred mathjax typesetting on startup to handle some dynamic content, and forgot to actually call the typeset method here.)
