### ISSUE TITLE
Possible mistake or lack of clarity in formula in chapter 2.

### ISSUE THREAD

**Issue by AjSat** [RussTedrake/underactuated#33]
In the final few paragraphs of chapter 2: a feedback linearization solution to stabilize pendulum in vertical position is presented. u = 2*g*cos(theta)/l. It is not clear how this input policy will stabilize the pendulum at theta = pi. Maybe the intended formula was u' = 2*g*cos(theta/2)/l?

**Comment by RussTedrake** [comment]
That's a bizarre typo.  Thank you for catching it.  The correct term should be `2mgl\sin(theta)`
