### ISSUE TITLE
pendulum torque_slider_demo Python script vs Jupyter notebook applied torque direction 

### ISSUE THREAD

**Issue by gedeschaines** [RussTedrake/underactuated#383]
Visualization of pendulum in the Python script is looking in direction of -Z axis, with +X to the right and +Y up; yielding +torque counterclockwise about +Z axis. Visualization of pendulum in the Jupyter notebook is looking in direction of +Y axis with +X to the right and +Z up; yielding +torque clockwise about the +Y axis. By making the following changes to torque_slider_demo.ipynb:
```
import numpy as np
T_VW = np.array([[-1., 0., 0., 0.],
                 [ 0., 0., 1., 0.],
                 [ 0., 0., 0., 1.]])
visualizer = builder.AddSystem(
    PlanarSceneGraphVisualizer(scene_graph, T_VW=T_VW, xlim=[-.7, .7], ylim=[-.7, .7], show=plt_is_interactive))
```
the direction of displayed pendulum motion in response to +/- torque slider values will correspond to counterclockwise/clockwise as expected with implied +X axis to the right, +Y axis up and +Z out of the display, toward the observer (or actually +X to the left, +Z up and +Y out of the display).

**Comment by RussTedrake** [comment]
Thanks.  I'd been meaning to fix this, and have done it now (though it' s now in MeshCat)
