### ISSUE TITLE
examples grid_world.ipynb TODO for drawing vector field

### ISSUE THREAD

**Issue by gedeschaines** [RussTedrake/underactuated#384]
Append following code cell to address the TODO "At very least, I want to draw the vector field of the resulting policy."
```
# Overlay the Policy input vector field on above Cost-to-Go plot.
Pi_X = np.reshape(policy.get_output_values()[0], X.shape)
Pi_Y = np.reshape(policy.get_output_values()[1], X.shape)
plt.quiver(X,Y,Pi_X,-Pi_Y)
plt.show()
```
Also consider changing ```ax.set_title("Cost-to-Go")``` to ```ax.set_title("Cost-to-Go (iteration 0)")``` and corresponding ```plt.title("iteration " + str(iteration))``` statement in the ```draw()``` procedure to ```plt.title("Cost-to-Go (iteration %d)" % iteration)```.

**Comment by RussTedrake** [comment]
Done. I've implemented the quiver (and some other small improvements).
