### ISSUE TITLE
Dynamic iteration count text for 3d plots in examples/double_integrator/value_iteration.ipynb

### ISSUE THREAD

**Issue by gedeschaines** [RussTedrake/underactuated#385]
To display dynamic iteration count text in Cost-to-Go and Policy 3d plots, insert following code blocks to the cells which define the ```min_time_cost()```(with ZMAX = 8.) and ```quadratic_regulator_cost()```(with ZMAX = 40.) functions after ```ax1.set_title("Cost-to-Go")``` and ```ax2.set_title("Policy")``` statements respectively:
```
ax1.set_xlim(qbins[0], qbins[-1])
ax1.set_ylim(qdotbins[0], qdotbins[-1])
ax1.set_zlim(0.,ZMAX)
iteration_text1 = ax1.text3D((qbins[-1]+qbins[0])/2, qdotbins[-1], ax1.get_zlim()[1], '')
```
```
ax2.set_xlim(qbins[0], qbins[-1])
ax2.set_ylim(qdotbins[0], qdotbins[-1])
ax2.set_zlim(-1.,1.)
iteration_text2 = ax2.text3D((qbins[-1]+qbins[0])/2, qdotbins[-1], ax2.get_zlim()[1], '')
```
Also replace ```plt.title("iteration " + str(iteration))``` statement in the ```draw()``` procedure with these two statements:
```
iteration_text1.set_text('iteration %03d' % iteration)
```
```
iteration_text2.set_text('iteration %03d' % iteration)
```
The first inserted before ```surf = ax1.plot_surface(Q, ...)``` statement and the second inserted before ```surf2 = ax2.plot_surface(Q, ...)``` statement.

**Comment by RussTedrake** [comment]
Thank you.  I've actually moved this visualization to meshcat, which is the most viable way I've found to update visualizations interactively on cloud jupyter notebooks.
