### ISSUE TITLE
Setup for Ubuntu 20.04 Focal

### ISSUE THREAD

**Issue by MAminSFV** [RussTedrake/underactuated#386]
It seems like the underactuated course supplement does not include an "install_prereqs.sh file" for ubuntu 20.04.

I was following the instructions on this page to run the  course material locally:

http://underactuated.csail.mit.edu/drake.html

Is it possible to use the course supplement on ubuntu focal in an alternative way?

Note: I have completed the binary setup for pydrake based on:
https://drake.mit.edu/python_bindings.html

**Comment by 2shaar2059** [comment]
As I was trying to build drake, I was getting dependency errors, specifically the libmumps one. Anyone else getting this?

**Comment by KeranYe** [comment]
@MAminSFV Did you resolve the problem? If so, could you share the solution?

**Comment by RussTedrake** [comment]
If you have problems installing drake, please post on stackoverflow. The
developers are quick to answer.

**Comment by RussTedrake** [comment]
20.04 is fully supported.
