### ISSUE TITLE
rename / relocate install scripts

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/underactuated#403]
drake has `install_prereqs.sh` (with extension) in the install tree, but the packaged version with the binaries is `install_prereqs` (no extension.  When I asked @jamiesnape about this, he said "Yes, executable scripts are not really supposed to have a suffix by Google style guide, but it is probably not worth fixing in Drake."

When I do change it, I can also move `scripts/setup/` to `setup/` and shorten the path for `ubuntu` like drake has done.

**Comment by RussTedrake** [comment]
(need to do this on the manipulation repo, too)

**Comment by jamiesnape** [comment]
Sounds good to me.
