### ISSUE TITLE
Notebook Setup failed on macOS 11.1

### ISSUE THREAD

**Issue by huangya17** [RussTedrake/underactuated#414]
Hello, 

Could you point me to the right direction as how to run the example on broswers / Notebook? 

I have following the instruction on 
https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/intro.ipynb#scrollTo=A4QOaw_zYLfI

But the installation stage failed persistently. Please see attached screen shot.

<img width="1743" alt="Screenshot 2021-02-24 at 12 39 21" src="https://user-images.githubusercontent.com/29413939/109002645-61a44d00-769e-11eb-878a-49d73d487b59.png">

Thank you

Ya

**Comment by RussTedrake** [comment]
You're doing the right thing.  Google colab upgraded from python3.6 to python3.7 yesterday and broke everything.  We are working feverishly to repair it.

**Comment by huangya17** [comment]
Thank you for the lightning reply! 

I will keep up my pace with the notes and video lectures.

Ya

**Comment by RussTedrake** [comment]
This should be completely resolved now.  (but please let me know if you find a notebook that fails).

**Comment by huangya17** [comment]
Many thanks! I have tried codes on ch1 ch2 and ch7 with no problem.
Bests,
Ya
