### ISSUE TITLE
`setup_drake` version is hard-coded

### ISSUE THREAD

**Issue by gizatt** [RussTedrake/underactuated#451]
I got confused why I wasn't getting recent Drake features in colab when using this method to install Drake + Underactuated -- I'm not 100% sure what version of underactuated is hosted on `underactuated.mit.edu`, but I'm guessing this might be why.

https://github.com/RussTedrake/underactuated/blob/9902038ead36b89c9c4687c1962cb6490b91fe7f/scripts/setup/setup_underactuated_colab.py#L96

(Is this residue from the Colab-Python-versions debacle, and that hardcoded version one custom-built to be compatible?)

**Comment by RussTedrake** [comment]
Yes.  It's residual, as the only way I can run drake on colab is from a custom built 3.7 binary.  :-(
