### ISSUE TITLE
cannot import name 'running_as_notebook' from 'underactuated'

### ISSUE THREAD

**Issue by littleggghost** [RussTedrake/underactuated#459]
Hi Professor

I use colab at
```
https://colab.research.google.com/github/RussTedrake/underactuated/blob/master/intro.ipynb#scrollTo=A4QOaw_zYLfI
```
and try to run the first block, but get the following error
```
ImportError: cannot import name 'running_as_notebook' from 'underactuated' (/usr/local/lib/python3.7/dist-packages/underactuated/__init__.py)
```
And I have installed this module `!pip install underactuated`

**Comment by RussTedrake** [comment]
Apologies.  I'll need to push a new wheel to pip; will do that today.  But this is a sign that I've transitioned to Deepnote as the primary workflow; colab support is now destined to lag a little behind.  

http://underactuated.csail.mit.edu/drake.html#notebooks

**Comment by RussTedrake** [comment]
I've pushed a new wheel.  It works now.  Please remember to use `!pip3 install underactuated` at the top of the notebook.
