### ISSUE TITLE
Some questions about trajectory optimization in littledog.ipynb

### ISSUE THREAD

**Issue by matheecs** [RussTedrake/underactuated#491]
1. What the meaning of "maximize cache hit" in `Create one context per timestep (to maximize cache hits)`?
2. How to implementing a few more Jacobians in MultibodyPlant to get rid it?

for instance:
```python
...
# Create one context per timestep (to maximize cache hits)
context = [plant.CreateDefaultContext() for i in range(N)]
# We could get rid of this by implementing a few more Jacobians in MultibodyPlant:
ad_plant = plant.ToAutoDiffXd()
...
```

**Comment by RussTedrake** [comment]
Related to: https://stackoverflow.com/questions/72095512/how-to-implement-custom-constraint-using-c

The context tries to avoid re-calculating kinematics, etc, when evaluating multiple output ports using the caching system.  By creating one context per timestep, I make it so calls to e.g. center of mass, to foot position, etc only have to call EvalKinematics once to compute all of their quantities.

The "for more Jacobians" was not advice for users, but to myself.  It is not an easy fix.
