### ISSUE TITLE
package.xml missing from distribution?

### ISSUE THREAD

**Issue by zouhairm** [RussTedrake/underactuated#513]
Sorry it's me again :)

After installing from github as described in #512 , I'm getting this error when running one of the notebooks
```
RuntimeError: PackageMap::GetPackageName(): Failed to parse XML in file "[.../lib/python3.11/site-packages/underactuated/package.xml)".
XML_ERROR_FILE_NOT_FOUND
```

I've fixed the issue by doing an editable install instead:
```
$ git clone https://github.com/RussTedrake/underactuated.git
$ pip3 install -e ./underactuated
```

I believe the issue is likely due to the https://github.com/RussTedrake/underactuated/blob/master/MANIFEST.in not including the package.xml file in the distribution.

**Comment by Eliah7** [comment]
Experiencing the same issue here.
