### ISSUE TITLE
Error Running the DeepNote of Ch 1

### ISSUE THREAD

**Issue by mlshehab** [RussTedrake/underactuated#528]
I'm duplicating the project (ch 1 in my case) and starting the machine, but I'm getting an import error:

ModuleNotFoundError: No module named 'pydrake' 
Even if I !pip install pydrake, I still get an error:
ModuleNotFoundError: No module named 'pydrake.all'

This is weird because the docker image should have the packages. Am I supposed to pip install anything to run the notebooks?

**Comment by RussTedrake** [comment]
Thanks for letting me know.  Something broke on deepnote and the change in the Drake dockerfile which added Drake to the pythonpath was being overwritten.

I've updated the dockerfile and updated all of the chapter notebooks.
Deepnote seems to have changed/broken their file upload, so I'll wait for them to fix that before manually updating the Dockerfile on all of the problem set notebooks.
