### ISSUE TITLE
Error in running UAV GCS AdvanceTo() visualization

### ISSUE THREAD

**Issue by verityw** [RussTedrake/underactuated#568]
I duplicated the [UAV GCS DeepNote notebook](https://deepnote.com/workspace/Underactuated-2ed1518a-973b-4145-bd62-1768b49956a8/project/10-Trajectory-Optimization-05031f8c-3586-4b47-be79-7f4893cf2f9d/notebook/gcs_quadrotor-dcbe8a11149940f8bfd9dcbb8b93df0e) and tried running it. While the solver does find a reasonable looking trajectory for the generated layout (when visualized by plotting), it seems like actually running the simulator errors out when `AdvanceTo()` is called:
```
IndexError                                Traceback (most recent call last)
Cell In [11], line 1
----> 1 uav_env.animate_trajectory(
      2     meshcat,
      3     [baseline_traj], # , shortest_path_traj],
      4     fly_in_sequence=False,
      5 )

File /usr/local/lib/python3.10/dist-packages/underactuated/uav_environment.py:1916, in UavEnvironment.animate_trajectory(self, meshcat, trajectories, fly_in_sequence, quadrotor_seperation)
   1914 if trajectories:
   1915     meshcat.StartRecording()
-> 1916     simulator.AdvanceTo(total_animation_duration)
   1917     meshcat.PublishRecording()
   1918 else:

IndexError: _Map_base::at
```
In particular, it seems like this happens when the UAV is about to enter the house -- see attached image from the default provided seed of 8.
<img width="867" alt="image" src="https://github.com/user-attachments/assets/4809da51-57ab-4b43-b080-369a91afc9a0">
I've found that this occurs in other seeds as well, and suspect it's due to collisions or something -- for seed 9, it looks like it crashes right as the drone's about to clip the side of the house:
![image](https://github.com/user-attachments/assets/b52fe74e-61c2-4262-9a0b-c6426cd73e24)
For reference, here's the full generated trajectory plotted in 2D:
![image](https://github.com/user-attachments/assets/3d5e285f-259f-4b61-9fa1-826f5192d1ba)
This looks correct, based on inspecting the rendered crashed environment's visualization of the random household (though I guess I don't know where the goal location for the UAV is in the household, since unlike the original gcs-science-robotics version, it doesn't have a cube marking the goal?)

Both the above examples are from just visualizing the baseline trajectory, not the shortest path one. I haven't changed anything in any of the cells, except to comment out the shortest path stuff and to only animate the baseline (though running the unaltered notebook similarly crashes at this point):
```
uav_env.animate_trajectory(
    meshcat,
    [baseline_traj], # , shortest_path_traj],
    fly_in_sequence=False,
)
```
I've also tried the Docker installation of the older gcs-science-robotics repo, and that seems to work.

**Comment by RussTedrake** [comment]
More details from Jeremy here: https://github.com/RobotLocomotion/drake/issues/22164#issuecomment-2479386488
