### ISSUE TITLE
planar_rigid_body_visualizer edgecolor is not visible

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/underactuated#61]
For the purely grey double pendulum, it makes for a pretty visually unappealing render.  Everything looks much sharper with the black edge. 

I see you've set edgecolor='k', but it's not working (at least not on my machine... though the pendulum works fine).  i spent a minute looking at it, but @gizatt would appreciate if you could take this one.

**Comment by RussTedrake** [comment]
i lied.  it's not showing up in my pendulumvisualizer either (though I'd swear that it was before?)

**Comment by gizatt** [comment]
fixed earlier today!
